# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: make dirs
      run: |
        mkdir scripts
        mkdir results
    - name: Checkout Scripts
      uses: actions/checkout@v4
      with:
        path: ./scripts
    - name: Checkout results
      uses: actions/checkout@v4
      with:
        path: ./scripts
    - name: Checkout branch minecraft-versions
      working-directory: results
      run: git checkout minecraft-versions
    - name: Checkout mcmeta
      run:  git clone -b data-json --single-branch https://github.com/misode/mcmeta.git
    - name: Run main_pipeline.py
      run: |
        cd scripts
        sudo apt update
        sudo apt install python[3.13]
        python -m venv venv
        . venv/bin/sctivate
        python main_pipeline.py
      
