# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: make dirs
      run: |
        mkdir scripts
        mkdir results
    - name: Checkout Scripts
      uses: actions/checkout@v4
      with:
        path: ./scripts
    - name: Checkout results
      uses: actions/checkout@v4
      with:
        path: ./results
        ref: minecraft-versions
    - name: Checkout mcmeta
      run:  git clone -b data-json --single-branch https://github.com/misode/mcmeta.git
    - name: Install python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13
    - name: Run main_pipeline.py
      run: |
        cd scripts
        sudo apt-get update
        python -m venv venv
        . venv/bin/activate
        echo python main_pipeline.py
      
